ALTER TABLE CUSTOMER ADD COLUMN USERNAME VARCHAR(50) NOT NULL UNIQUE;
ALTER TABLE CUSTOMER ADD COLUMN EMAIL VARCHAR(100) NOT NULL;
ALTER TABLE CUSTOMER ADD COLUMN PASSWORD VARCHAR(64) NOT NULL;
ALTER TABLE CUSTOMER ADD COLUMN CITY VARCHAR(100) NOT NULL;
ALTER TABLE CUSTOMER ADD COLUMN DOB DATE NOT NULL;
